// <auto-generated />
using System;
using JueriShop.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JueriShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220525091845_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JueriShop.Models.Category", b =>
                {
                    b.Property<int>("IdCateg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCateg"), 1L, 1);

                    b.Property<string>("Category_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JewelryIdJewel")
                        .HasColumnType("int");

                    b.Property<int?>("JewelryIdOrdIt")
                        .HasColumnType("int");

                    b.HasKey("IdCateg");

                    b.HasIndex("JewelryIdJewel");

                    b.HasIndex("JewelryIdOrdIt");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("JueriShop.Models.Jewelry", b =>
                {
                    b.Property<int>("IdJewel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJewel"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderItemIdOrdIt")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.HasKey("IdJewel");

                    b.HasIndex("OrderItemIdOrdIt");

                    b.ToTable("jewels");
                });

            modelBuilder.Entity("JueriShop.Models.OrderItem", b =>
                {
                    b.Property<int>("IdOrdIt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdIt"), 1L, 1);

                    b.Property<int>("IdJewelry")
                        .HasColumnType("int");

                    b.Property<int>("UserOrder")
                        .HasColumnType("int");

                    b.HasKey("IdOrdIt");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("JueriShop.Models.OrderStatus", b =>
                {
                    b.Property<int>("IdOrdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdStatus"), 1L, 1);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserOrderIdUOrder")
                        .HasColumnType("int");

                    b.HasKey("IdOrdStatus");

                    b.HasIndex("UserOrderIdUOrder");

                    b.ToTable("orderStatuses");
                });

            modelBuilder.Entity("JueriShop.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserOrderIdUOrder")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("UserOrderIdUOrder");

                    b.ToTable("users");
                });

            modelBuilder.Entity("JueriShop.Models.UserOrder", b =>
                {
                    b.Property<int>("IdUOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUOrder"), 1L, 1);

                    b.Property<string>("DeliverAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderItemIdOrdIt")
                        .HasColumnType("int");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdUOrder");

                    b.HasIndex("OrderItemIdOrdIt");

                    b.ToTable("userOrders");
                });

            modelBuilder.Entity("JueriShop.Models.Category", b =>
                {
                    b.HasOne("JueriShop.Models.Jewelry", null)
                        .WithMany("Categories")
                        .HasForeignKey("JewelryIdJewel");

                    b.HasOne("JueriShop.Models.OrderItem", "Jewelry")
                        .WithMany()
                        .HasForeignKey("JewelryIdOrdIt");

                    b.Navigation("Jewelry");
                });

            modelBuilder.Entity("JueriShop.Models.Jewelry", b =>
                {
                    b.HasOne("JueriShop.Models.OrderItem", "OrderItem")
                        .WithMany("jewelries")
                        .HasForeignKey("OrderItemIdOrdIt");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("JueriShop.Models.OrderStatus", b =>
                {
                    b.HasOne("JueriShop.Models.UserOrder", "UserOrder")
                        .WithMany("orderStatuses")
                        .HasForeignKey("UserOrderIdUOrder");

                    b.Navigation("UserOrder");
                });

            modelBuilder.Entity("JueriShop.Models.User", b =>
                {
                    b.HasOne("JueriShop.Models.UserOrder", "UserOrder")
                        .WithMany("users")
                        .HasForeignKey("UserOrderIdUOrder");

                    b.Navigation("UserOrder");
                });

            modelBuilder.Entity("JueriShop.Models.UserOrder", b =>
                {
                    b.HasOne("JueriShop.Models.OrderItem", "OrderItem")
                        .WithMany("userOrders")
                        .HasForeignKey("OrderItemIdOrdIt");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("JueriShop.Models.Jewelry", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("JueriShop.Models.OrderItem", b =>
                {
                    b.Navigation("jewelries");

                    b.Navigation("userOrders");
                });

            modelBuilder.Entity("JueriShop.Models.UserOrder", b =>
                {
                    b.Navigation("orderStatuses");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
